# Generated by Django 5.0.6 on 2024-06-19 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('intercom', models.CharField(max_length=100)),
                ('number_of_floors', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('passport_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('base_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('area', models.FloatField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.building')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.object'),
        ),
        migrations.AddField(
            model_name='object',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.objecttype'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('comments', models.TextField()),
                ('total_cost', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.client')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.employee')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.status')),
            ],
        ),
        migrations.CreateModel(
            name='CleanerOrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wage', models.FloatField()),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.cleaner')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.order')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.position'),
        ),
        migrations.CreateModel(
            name='ReplacementCleanerOrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wage', models.FloatField()),
                ('comment', models.TextField()),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_cleaner', to='analytics.cleaner')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.order')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('height', models.FloatField()),
                ('comment', models.TextField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.object')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.roomform')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('comment', models.TextField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.object')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.service')),
            ],
        ),
        migrations.CreateModel(
            name='FloorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('comment', models.TextField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.floor')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.operation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('services', models.ManyToManyField(to='analytics.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.room')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.service')),
            ],
        ),
        migrations.CreateModel(
            name='CleanerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.cleaner')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.skill')),
            ],
        ),
        migrations.AddField(
            model_name='cleaner',
            name='skills',
            field=models.ManyToManyField(through='analytics.CleanerSkill', to='analytics.skill'),
        ),
        migrations.CreateModel(
            name='ServiceSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.service')),
                ('surface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.surface')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.team'),
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.cleaner')),
                ('time_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.timetype')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.room')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.service')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.zone')),
            ],
        ),
    ]
