# Generated by Django 5.0.6 on 2024-06-20 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_savedreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanerorderassignment',
            name='cleaner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.employee'),
        ),
    ]
