# Generated by Django 5.0.6 on 2024-06-20 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_cleanerorderassignment_cleaner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaner',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cleanerorderassignment',
            name='cleaner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.cleaner'),
        ),
    ]
