# Generated by Django 5.0.6 on 2024-06-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_cleaner_team_alter_cleanerorderassignment_cleaner'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='data_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
