# Generated by Django 5.0.6 on 2024-06-21 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_savedreport_data_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedReport',
        ),
    ]
